# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ProofOfConcept' do
    use_frameworks!

# Pods for ProofOfConcept
    pod 'ReachabilitySwift'

end